# NOTE: update this with your service name
service: team-reads-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  profile: team-reads
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  # Respondents
  createBook:
    handler: functions/books/create.main
    warmup: true
    events:
      - http:
          path: book
          method: post
          private: false
          cors: true
  listBooks:
    handler: functions/books/list.main
    warmup: true
    events:
      - http:
          path: book
          method: get
          private: false
          cors: true
  findBook:
    handler: functions/books/find.main
    warmup: true
    events:
      - http:
          path: book/{id}
          method: get
          private: false
          cors: true
  deleteBook:
    handler: functions/books/delete.main
    warmup: true
    events:
      - http:
          path: book/{id}
          method: delete
          private: false
          cors: true
## Note
  createNote:
    handler: functions/notes/create.main
    warmup: true
    events:
      - http:
          path: book
          method: post
          private: false
          cors: true
  listNotes:
    handler: functions/notes/list.main
    warmup: true
    events:
      - http:
          path: book
          method: get
          private: false
          cors: true
  findNote:
    handler: functions/notes/find.main
    warmup: true
    events:
      - http:
          path: book/{id}
          method: get
          private: false
          cors: true
  deleteNote:
    handler: functions/notes/delete.main
    warmup: true
    events:
      - http:
          path: book/{id}
          method: delete
          private: false
          cors: Note
