# NOTE: update this with your service name
service: team-reads-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  profile: team-reads
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to env.yml and uncomment
  # the following line. Also, make sure to not
  # commit your env.yml.
  #
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  # Respondents
  createBook:
    handler: functions/books/create.main
    warmup: true
    events:
      - http:
          path: book
          method: post
          privat: false
          cors: true
  listBooks:
    handler: functions/books/list.main
    warmup: true
    events:
      - http:
          path: book
          method: get
          privat: false
          cors: true
  findBook:
    handler: functions/books/find.main
    warmup: true
    events:
      - http:
          path: book/{id}
          method: get
          privat: false
          cors: true
  deleteBook:
    handler: functions/books/delete.main
    warmup: true
    events:
      - http:
          path: book/{id}
          method: delete
          privat: false
          cors: true
  updateBook:
    handler: functions/books/update.main
    warmup: true
    events:
      - http:
          path: book/{id}
          method: put
          privat: false
          cors: true
# Shelves
  createShelf:
    handler: functions/shelves/create.main
    warmup: true
    events:
      - http:
          path: shelf
          method: post
          privat: false
          cors: true
  listShelves:
    handler: functions/shelves/list.main
    warmup: true
    events:
      - http:
          path: shelf
          method: get
          privat: false
          cors: true
  findShelf:
    handler: functions/shelves/find.main
    warmup: true
    events:
      - http:
          path: shelf/{id}
          method: get
          privat: false
          cors: true
  deleteShelf:
    handler: functions/shelves/delete.main
    warmup: true
    events:
      - http:
          path: shelf/{id}
          method: delete
          privat: false
          cors: true
  updateShelf:
    handler: functions/shelves/update.main
    warmup: true
    events:
      - http:
          path: shelf/{id}
          method: put
          privat: false
          cors: true
# Teams
  createTeam:
    handler: functions/teams/create.main
    warmup: true
    events:
      - http:
          path: team
          method: post
          privat: false
          cors: true
  listTeams:
    handler: functions/teams/list.main
    warmup: true
    events:
      - http:
          path: team
          method: get
          privat: false
          cors: true
  findTeam:
    handler: functions/teams/find.main
    warmup: true
    events:
      - http:
          path: team/{id}
          method: get
          privat: false
          cors: true
  deleteTeam:
    handler: functions/teams/delete.main
    warmup: true
    events:
      - http:
          path: team/{id}
          method: delete
          privat: false
          cors: true
  updateTeam:
    handler: functions/teams/update.main
    warmup: true
    events:
      - http:
          path: team/{id}
          method: put
          privat: false
          cors: true
  # Users
  createUser:
    handler: functions/users/create.main
    warmup: true
    events:
      - http:
          path: user
          method: post
          privat: false
          cors: true
  listUsers:
    handler: functions/users/list.main
    warmup: true
    events:
      - http:
          path: user
          method: get
          privat: false
          cors: true
  findUser:
    handler: functions/users/find.main
    warmup: true
    events:
      - http:
          path: user/{id}
          method: get
          privat: false
          cors: true
  deleteUser:
    handler: functions/users/delete.main
    warmup: true
    events:
      - http:
          path: user/{id}
          method: delete
          privat: false
          cors: true
  updateUser:
    handler: functions/users/update.main
    warmup: true
    events:
      - http:
          path: user/{id}
          method: put
          privat: false
          cors: true
  # Comments
  createComment:
    handler: functions/comments/create.main
    warmup: true
    events:
      - http:
          path: comment
          method: post
          privat: false
          cors: true
  listComments:
    handler: functions/comments/list.main
    warmup: true
    events:
      - http:
          path: comment
          method: get
          privat: false
          cors: true
  findComment:
    handler: functions/comments/find.main
    warmup: true
    events:
      - http:
          path: comment/{id}
          method: get
          privat: false
          cors: true
  deleteComment:
    handler: functions/comments/delete.main
    warmup: true
    events:
      - http:
          path: comment/{id}
          method: delete
          privat: false
          cors: true
  updateComment:
    handler: functions/comments/update.main
    warmup: true
    events:
      - http:
          path: comment/{id}
          method: put
          privat: false
          cors: true
  # Discussion
  createDiscussion:
    handler: functions/discussions/create.main
    warmup: true
    events:
      - http:
          path: discussion
          method: post
          privat: false
          cors: true
  listDiscussions:
    handler: functions/discussions/list.main
    warmup: true
    events:
      - http:
          path: discussion
          method: get
          privat: false
          cors: true
  findDiscussion:
    handler: functions/discussions/find.main
    warmup: true
    events:
      - http:
          path: discussion/{id}
          method: get
          privat: false
          cors: true
  deleteDiscussion:
    handler: functions/discussions/delete.main
    warmup: true
    events:
      - http:
          path: discussion/{id}
          method: delete
          privat: false
          cors: true
  updateDiscussion:
    handler: functions/discussions/update.main
    warmup: true
    events:
      - http:
          path: discussion/{id}
          method: put
          privat: false
          cors: true
